### ISSUE TITLE
License missing & related project

### ISSUE THREAD

**Issue by matthijskooijman** [tbowmo/ice3breakout#4]
Some time ago, I created a similar board (with fewer features), that might be interesting to you, see https://github.com/matthijskooijman/jtagice3-converter-board. One thing that might be useful is the mounting hole placement, my design has them aligned with the mounting holes of the JTAGICE3 PCB, allowing to solidly connect the PCB through the case to the existing PCB.

I might be updating my design in the near future for the Atmel ICE programmer and I'll probably borrow some of your ideas, but I'm missing a license on your repository. The PCB says "OSHW", but without a proper grant of license, that logo is not meaningful. Did I miss the license details, or should you add them?

**Comment by tbowmo** [comment]
Almost forgot about this project, even though I use it regularly.. Had plans for selling assembled boards, but never got around to it (I have too many projects going on at the same time)

I haven't disassembled my jtagice3, so didn't check the mounting holes of the board inside.. But a good poin though.

I'll add licensing files
